# Aljabar Matrik
1. Berikan penjelasan tentang apa itu matrix
1. Penjumlahan perkalian, pengurangan, transpose matrik
2. Operasi matrik
3. Buat program untuk mengalikan matrik a dan b

# Pengertian Matriks

**Matriks** adalah struktur data yang terdiri dari sejumlah bilangan yang diatur dalam format baris dan kolom. Dalam matriks, elemen-elemen ini disusun sedemikian rupa sehingga membentuk m baris dan n kolom.

**Contoh**

In [1]:
import numpy as np

In [11]:
a=np.array([[1,3,9],[3,-2,6],[9,4,1]]) # matriks 3x3
b=np.array([[1,7,5],[2,4,5],[1,-1,4]]) # matriks 3x3
c=np.array([[3,2],[-1,2],[3,5]]) # matriks 3x2
d=np.array([[2,4,8],[2,-1,5],[-8,5,2]]) # matriks 3x3
e=2*(a)
f=(a+b)
g=a @ c

In [12]:
print(f"matriks a 3x3: \n{a}")
print(f"matriks b 3x3: \n{b}")
print(f"matriks c 3x2: \n{c}")
print(f"matriks d 3x3: \n{d}")

matriks a 3x3: 
[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]
matriks b 3x3: 
[[ 1  7  5]
 [ 2  4  5]
 [ 1 -1  4]]
matriks c 3x2: 
[[ 3  2]
 [-1  2]
 [ 3  5]]
matriks d 3x3: 
[[ 2  4  8]
 [ 2 -1  5]
 [-8  5  2]]


#Penjumlahan Matriks

In [16]:
# Penjumlahan Matriks A + B
f=(a+b)
print(f'matriks f=\n{f}')

matriks f=
[[ 2 10 14]
 [ 5  2 11]
 [10  3  5]]


#Pengurangan Matriks

In [15]:
# Pengurangan Matriks A - B
h=(a-b)
print(f"matriks g=\n{h}")

matriks g=
[[ 0 -4  4]
 [ 1 -6  1]
 [ 8  5 -3]]


# Perkalian Matriks

In [18]:
e=2*(a)
print(f'perkalian 2 dikali matriks e=\n{e}')

perkalian 2 dikali matriks e=
[[ 2  6 18]
 [ 6 -4 12]
 [18  8  2]]


# Tranpose Matriks

In [20]:
# Matriks A
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose Matriks A
a_tran = a.transpose()

# Menampilkan Matriks A dan A_transpose
print("Matriks A:")
print(a)

print("Matriks A Transpose:")
print(a_tran)

# Menghitung Z = A_transpose * A
z=a_tran @ a

# Menampilkan Matriks Z
print("Matriks Z (A_transpose * A):")
print(z)

# Menghitung P = A * A_transpose
p=a @ a_tran

# Menampilkan Matriks P
print("Matriks P (A * A_transpose):")
print(p)

Matriks A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks A Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matriks Z (A_transpose * A):
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
Matriks P (A * A_transpose):
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


# Program Perkalian Matriks A dan B

In [23]:
# Matriks A
a=[[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# Matriks B
b=[[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

# Hasil
hasil=[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            hasil[i][j] += a[i][k] * b[k][j]
print("Hasil perkalian Matriks A dan B:")
for baris in hasil:
  print(baris)

Hasil perkalian Matriks A dan B:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]
