# **Aljabar Matrik**
1. Berikan penjelasan tentang apa itu matrix
1. Penjumlahan perkalian, pengurangan, transpose matrik
2. Operasi matrik
3. Buat program untuk mengalikan matrik a dan b

#### **Pengertian Matriks**

**Matriks** adalah struktur data yang terdiri dari sejumlah bilangan yang diatur dalam format baris dan kolom, serta ditempatkan di dalam tanda kurung, tanda kurungnya bisa "( )" atau kurung siku "[ ]".

Dalam matriks, elemen-elemen ini disusun sedemikian rupa sehingga membentuk m baris dan n kolom.

Setiap matriks memiliki dua ciri penting: Ordo dan Elemen. Ordo matriks menunjukkan berapa banyak baris dan kolom yang ada di tabel. Contohnya, matriks dengan ordo 2x3 (dibaca "dua kali tiga") memiliki dua baris dan tiga kolom.

**Contoh**

$
\begin{align*}
A=
\begin{bmatrix}
1&3&9\\
3&-1&6\\
9&4&1
\end{bmatrix}
\end{align*}
$

$
\begin{align*}
B=
\begin{bmatrix}
1&7&5\\
2&4&5\\
1&-1&4
\end{bmatrix}
\end{align*}
$

$
\begin{align*}
C=
\begin{bmatrix}
3&2\\
-1&2\\
3&-5
\end{bmatrix}
\end{align*}
$

$
\begin{align*}
D=
\begin{bmatrix}
2&4&8\\
2&-1&5\\
-8&5&2
\end{bmatrix}
\end{align*}
$

In [1]:
import numpy as np

In [2]:
a=np.array([[1,3,9],[3,-2,6],[9,4,1]]) # matriks 3x3
b=np.array([[1,7,5],[2,4,5],[1,-1,4]]) # matriks 3x3
c=np.array([[3,2],[-1,2],[3,5]]) # matriks 3x2
d=np.array([[2,4,8],[2,-1,5],[-8,5,2]]) # matriks 3x3
e=2*(a)
f=(a+b)
g=a @ c

In [3]:
print(f"matriks a 3x3: \n{a}")
print(f"matriks b 3x3: \n{b}")
print(f"matriks c 3x2: \n{c}")
print(f"matriks d 3x3: \n{d}")

matriks a 3x3: 
[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]
matriks b 3x3: 
[[ 1  7  5]
 [ 2  4  5]
 [ 1 -1  4]]
matriks c 3x2: 
[[ 3  2]
 [-1  2]
 [ 3  5]]
matriks d 3x3: 
[[ 2  4  8]
 [ 2 -1  5]
 [-8  5  2]]


#### **Penjumlahan Matriks**

Kombinasi Matriks: Menggabungkan Dua Matriks yang Sama Ukurannya
Bayangkan kita punya dua kotak berisi angka yang tersusun rapi dengan jumlah baris dan kolom yang sama. Operasi kombinasi matriks ibarat menggabungkan kedua kotak tersebut, menghasilkan kotak baru dengan susunan angka yang sama.

**Syarat Kombinasi Matriks:**

- Ukuran Sama: Kedua kotak angka (matriks) harus memiliki jumlah baris dan kolom yang sama. Ibarat kotak, jumlah rak dan kolomnya harus sama.
- Angka di Posisi Sama: Angka-angka yang ingin digabungkan harus berada di posisi yang sama pada kedua kotak. Ibarat kotak, angka di rak dan kolom yang sama pada kedua kotak digabungkan.pada posisi yang sama pada kedua matriks.
Ulangi langkah 2 untuk semua elemen pada kedua matriks.

**Contoh:**


In [4]:
# Penjumlahan Matriks A + B
f=(a+b)
print(f'matriks f=\n{f}')

matriks f=
[[ 2 10 14]
 [ 5  2 11]
 [10  3  5]]


####**Pengurangan Matriks**

**Pengurangan Matriks** adalah sebuah operasi matematika yang melibatkan dua matriks atau lebih.

Dalam operasi ini kita harus mengurangi elemen-elemen yang ada pada pada posisi yang sama pada matriks tersebut.

**Syarat Pengurangan Matriks:**

1. Ukuran Yang Sama.
2. Elemen Matriks Yang Baru.
3. Sifat Pengurangan Matriks:
- Komutatif: (A-B = B-A)
- Asosiatif: ((A-B)-C = A-(B+C))
- Matriks Nol/Identitas: (A - O = O - A = A)
- Lawan Matriks: (A - B = A + (-B))

**Contoh:**



In [5]:
# Pengurangan Matriks A - B
h=(a-b)
print(f"matriks g=\n{h}")

matriks g=
[[ 0 -4  4]
 [ 1 -6  1]
 [ 8  5 -3]]


#### **Perkalian Matriks**

Perkalian Matriks dapat dilakukan dengan melibatkan dua matriks dan menghasilkan matriks baru. Berbeda dengan penjumlahan serta pengurangan matriks, perkalian matriks melibatkan operasi perkalian dan penjumlahan.

**Syarat Perkalian Matriks:**
- **Kesamaan/Kesesuaian Dimensi:** Matriks pertama harus punya jumlah kolom yang sama dengan matriks kedua. Jika matriks pertama punya dimensi (m x n) dan matriks kedua punya dimensi (p x q), maka n harus sama dengan p agar kedua matriks bisa dikalikan.
- **Hasil Matriks:** Matriks hasil perkalian akan punya dimensi (m x q), di mana m adalah jumlah baris pada matriks pertama dan q adalah jumlah kolom pada matriks kedua.

**Contoh:**

In [ ]:
e=2*(a)
print(f'perkalian 2 dikali matriks e=\n{e}')

perkalian 2 dikali matriks e=
[[ 2  6 18]
 [ 6 -4 12]
 [18  8  2]]


# Tranpose Matriks

In [ ]:
# Matriks A
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose Matriks A
a_tran = a.transpose()

# Menampilkan Matriks A dan A_transpose
print("Matriks A:")
print(a)

print("Matriks A Transpose:")
print(a_tran)

# Menghitung Z = A_transpose * A
z=a_tran @ a

# Menampilkan Matriks Z
print("Matriks Z (A_transpose * A):")
print(z)

# Menghitung P = A * A_transpose
p=a @ a_tran

# Menampilkan Matriks P
print("Matriks P (A * A_transpose):")
print(p)

Matriks A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks A Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matriks Z (A_transpose * A):
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
Matriks P (A * A_transpose):
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


#### **Program Perkalian Matriks A dan B Tanpa @**

In [1]:
Matrix_1 = [[1,3,9],
            [3,-2,6],
            [9,4,1]]

Matrix_2 = [[1,7,5],
            [2,4,5],
            [1,-1,4]]

print(f"Matrix_1 = {Matrix_1}")
print()
print(f"Matrix_2 = {Matrix_2}")

def multiply_matrix(matrix1, matrix2):
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))] # Memperbaiki inisialisasi hasil

    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j] # Menggunakan parameter fungsi

    return result

hasil = multiply_matrix(Matrix_1, Matrix_2)
print()
print(f"Hasil perkalian Matrix_1 dan Matrix_2 = {hasil}")


Matrix_1 = [[1, 3, 9], [3, -2, 6], [9, 4, 1]]

Matrix_2 = [[1, 7, 5], [2, 4, 5], [1, -1, 4]]

Hasil perkalian Matrix_1 dan Matrix_2 = [[16, 10, 56], [5, 7, 29], [18, 78, 69]]
