# Determinant Matriks

**Sifat-sifat Determinan Matriks**

**1. Ordo Matriks Harus Sama**

Determinan hanya dapat dihitung pada **matriks persegi**, yaitu matriks yang memiliki jumlah baris dan kolom sama. Jika matriksnya tidak persegi, maka tidak memiliki determinan.

**2. Determinan Matriks Identitas**

Determinan dari **matriks identitas** (matriks yang diagonal utamanya berisi 1 dan elemen lainnya berisi 0) selalu **sama dengan 1**.

**3. Pengaruh Penukaran Baris pada Determinan**

Menukar dua baris pada matriks akan **mengubah tanda determinan**.

**4. Determinan Matriks dengan Baris/Kolom Kelipatan**

Jika sebuah baris atau kolom pada matriks merupakan **kelipatan k** dari baris atau kolom lain, maka determinan matriks tersebut akan **sama dengan k kali determinan matriks asli**.

* Contoh: Misalkan determinan matriks A = 5. Jika matriks B memiliki baris yang merupakan kelipatan 2 dari baris matriks A, maka determinan matriks B = 2 * 5 = 10.

**5. Pengaruh Penggandaan Baris/Kolom pada Determinan**

Menggandakan sebuah baris atau kolom pada matriks dengan **faktor skalar k** akan **mengubah determinan matriks menjadi k kali determinan asli**.

* Contoh: Misalkan determinan matriks A = -5. Jika baris pertama matriks A dikalikan dengan 2, maka determinan matriks hasil (A') = 2 * -5 = -10.

**6. Determinan Matriks dengan Baris/Kolom Kelipatan dan Pengurangan**

Jika dua baris atau kolom pada matriks merupakan **kelipatan k** dari baris atau kolom lain **dan salah satunya dikurangkan dengan yang lain**, maka determinan matriks tersebut akan **sama dengan 0**.

* Contoh: Misalkan matriks A =
```
[3 4 2 1]
[4 7 2 1]
```
Jika kolom pertama matriks A dikurangkan dengan kolom kedua, maka determinan matriks hasil = 0.

**7. Determinan Matriks Segitiga Atas/Bawah dan Matriks Diagonal**

Determinan dari **matriks segitiga atas/bawah** atau **matriks diagonal** sama dengan **hasil kali elemen-elemen pada diagonal utama**.

**Contoh:**

Misalkan matriks A =
```
[3 0 0]
[0 2 0]
[0 0 1]
```
Determinan matriks A = 3 * 2 * 1 = 6.

**Kesimpulan:**

Sifat-sifat determinan matriks ini penting untuk dipahami dalam mempelajari aljabar linear. Sifat-sifat ini dapat digunakan untuk menghitung determinan matriks dengan lebih mudah dan efisien, serta untuk memahami berbagai konsep dalam matematika.


In [ ]:
import numpy as np
a = np. array (([1,0],[0,1]))
b = np.array(([1,0,0],[0,1,0],[0,0,1]))
c = np.array(([1,2,1],[3,1,2],[2,1,2]))
d = np.array(([1,2,1],[1,2,1],[2,1,2]))
e = np.array (([1,2,1],[2,4,2],[2,1,2]))
f = np.array (([1,2,1],[2,4,2],[2,4,3]))
g = np.array (([6,2,4],[2,4,2],[4,2,3]))
h = np.array (([6,8],[4,2]))
i = np.array (([6,8],[2,1]))
j = np.array (([6,4],[4,1]))
k = np.array(([[3,1,3],[2,1,2],[4,2,1]]))


det_a = np.linalg.det(a)
det_b = np.linalg.det(b)
det_c = np.linalg.det(c)
det_d = np.linalg.det(d)
det_e = np.linalg.det(e)
det_f = np.linalg.det(f)
det_g = np.linalg.det(g)
det_h = np.linalg.det(h)
det_i = np.linalg.det(i)
det_j = np.linalg.det(j)
det_k = np.linalg.det(k)


print('Matriks A = ',a)
print('Matriks B = ',b)
print('Matriks C = ',c)
print('Matriks D = ',d)
print('Matriks E = ',e)
print('Matriks F = ',f)
print('Matriks G = ',g)
print('Matriks H = ',h)
print('Matriks I = ',i)
print('Matriks J = ',j)



print('Determinant A = ',det_a)
print('Determinant B = ',det_b)
print('Determinant C = ',det_c)
print('Determinant D = ',det_d)
print('Determinant E = ',det_e)
print('Determinant F = ',det_f)
print('Determinant G = ',det_g)
print('Determinant H = ',det_h)
print('Determinant I = ',det_i)
print('Determinant J = ',det_j)
print('Determinant K = ',det_k)

Matriks A =  [[1 0]
 [0 1]]
Matriks B =  [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matriks C =  [[1 2 1]
 [3 1 2]
 [2 1 2]]
Matriks D =  [[1 2 1]
 [1 2 1]
 [2 1 2]]
Matriks E =  [[1 2 1]
 [2 4 2]
 [2 1 2]]
Matriks F =  [[1 2 1]
 [2 4 2]
 [2 4 3]]
Matriks G =  [[6 2 4]
 [2 4 2]
 [4 2 3]]
Matriks H =  [[6 8]
 [4 2]]
Matriks I =  [[6 8]
 [2 1]]
Matriks J =  [[6 4]
 [4 1]]
Matriks K =  [[3 1 3]
 [2 1 2]
 [4 2 1]]
Determinant A =  1.0
Determinant B =  1.0
Determinant C =  -3.000000000000001
Determinant D =  0.0
Determinant E =  0.0
Determinant F =  0.0
Determinant G =  4.000000000000005
Determinant H =  -19.999999999999996
Determinant I =  -9.999999999999998
Determinant J =  -9.999999999999998
Determinant K =  -2.9999999999999996


**COFACTOR**

Dalam matriks, kofaktor adalah determinan matriks yang diperoleh dengan menghilangkan baris dan kolom tempat elemen tersebut berada.  Nilai kofaktor ditentukan oleh posisi elemen, dengan perkalian +1 atau -1.  Setiap elemen dalam matriks memiliki kofaktor yang terkait.  Misalnya, kofaktor elemen pada posisi (1,1) didapatkan dengan menghilangkan baris ke-1 dan kolom ke-1, kemudian menghitung determinan matriks yang tersisa.

**Menghitung Invers Matriks 5x5 dengan Kofaktor**

Berikut adalah Matriks 5x5

$
\begin{align*}
S=
\begin{bmatrix}
1&1&2&3&1\\
1&3&2&2&3\\
1&1&1&1&2\\
2&4&2&3&2\\
2&2&3&3&1
\end{bmatrix}
\end{align*}
$

**Mencari Matriks Invers**

Rumus

* Kofaktor = $C_{ij} = (-1)^{i+j} * detS$

* DET = $a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{nn} * c_{nn}$

* Invers Matriks = ${ \frac{1}{detS}} * adj(S)$

* Cari Adjoin = $adj(S) = (kof(A))^T$

* (adj(S) = Transpose dari tiap Kofaktor Matriks

In [ ]:
import numpy as np  # Kita akan menggunakan library NumPy untuk perhitungan matriks

# Inisialisasi matriks S
S = np.array([
    [1, 1, 2, 3, 1],
    [1, 3, 2, 2, 3],
    [1, 1, 1, 1, 2],
    [2, 4, 2, 3, 2],
    [2, 2, 3, 3, 1]
])

# Fungsi untuk menghitung determinan matriks (hanya untuk matriks 2x2)
def det2x2(matrix):
    return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

# Fungsi untuk menghitung kofaktor
def kofaktor(matrix, i, j):
    submatrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)  # Hapus baris i dan kolom j
    return (-1)**(i+j) * det2x2(submatrix)

# Fungsi untuk menghitung determinan matriks 5x5
def det5x5(matrix):
    det = 0
    for j in range(5):
        det += matrix[0, j] * kofaktor(matrix, 0, j)
    return det

# Fungsi untuk menghitung adjoin matriks
def adjoin(matrix):
    adj = np.zeros((5, 5))
    for i in range(5):
        for j in range(5):
            adj[i, j] = kofaktor(matrix, j, i)  # Perhatikan penukaran indeks i dan j
    return adj

# Hitung determinan dan invers
det_S = det5x5(S)
if det_S != 0:
    inv_S = (1 / det_S) * adjoin(S)
    print("Invers matriks S:")
    print(inv_S)
else:
    print("Matriks S tidak memiliki invers (determinan nol)")

Invers matriks S:
[[ 0.5  0.5 -2.   2.  -2. ]
 [ 0.5 -0.5  0.   0.   0. ]
 [-1.   0.   1.  -1.   1. ]
 [ 1.   0.  -1.   1.  -1. ]
 [-1.   0.   1.  -1.   1. ]]


In [ ]:
bikin matriks yang membawa nilai 1,0 dimana akan dibawa ke minus 1,0. 2,2 jadi minus 2,2

In [ ]:
nilai 2,0 ke -2,0